### ISSUE TITLE
The idea behind the game is outstanding , but what i found is that there is no way for user to quit game. Also the position of the grid is not correct.  

### ISSUE THREAD

**Issue by Udhay-Brahmi** [Nonparoxysmic/SmallUnityGames#3]
#2 ( SOLVED, PLZ MERGE MY PR)

**Comment by Nonparoxysmic** [comment]
Thank you for your feedback. Your criticisms are true, because this game is still in development and far from finished. I am not looking for contributions right now, but I will consider your suggestions when I return to developing this. Have a nice day.
